export default {
  font: {
    family:
      "Poppins, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif",
    sizes: {
      small: "1.0rem",
      xsmall: "1.2rem",
      medium: "1.5rem",
      large: "1.8rem",
      xlarge: "2.0rem",
      xxlarge: "2.8rem",
      xxxlarge: "3.6rem",
      huge: "6rem",
      xhuge: "10rem",
      xxhuge: "16rem",
      xxxhuge: "20rem",
    },
  },
  colors: {
    primary: "#5b1e17",
    primaryMedium: "#805e5a",
    primaryLight: "#cdbbb9",
    secondary: "#f1e3e2",
    secondaryMedium: "#ffffff",
    secondaryLight: "#0DC79F",
    darkBlack: "#1A1A1A",
    dangerDark: "#BC0000",
    dangerMedium: "#F50000",
    dangerLight: "#F56C6C",
    white: "#FFF",
    black: "#141414",
    gray: "#8F8F8F",
    gradient: "linear-gradient(90deg, #0B80AD 0%, #0FAEEB 50%)",
  },
} as const;